const TAG = 'GLOB_';
export const API_LOADING_START = TAG + 'API_LOADING_START';
export const API_LOADING_STOP = TAG + 'API_LOADING_STOP';
export const IS_INTERNET_CONNECTED = TAG + 'IS_INTERNET_CONNECTED';
export const THEM_LOADER_STRAT = 'THEM_LOADER_STRAT';
export const THEM_LOADER_STOP = 'THEM_LOADER_STOP';
export const SAVE_APP_CONFIG = 'SAVE_APP_CONFIG';
