export const userData = "@userData"
export const guestData = "@guestData"
export const accessToken = "@accessToken"
export const isFirstTimeOpen = "@isFirstTimeOpen"
export const isTermsSelected = "@isTermsSelected"
export const faceSwipCount = "@faceSwipCount"
export const appSettings = "@appSettings"